-- CHAT DB 
CREATE TABLE `MEMBER` (
  `MEMBER_SEQ` int(11) NOT NULL,
  `EMAIL` varchar(500) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `USERNAME` varchar(100) NOT NULL,
  `DEFAULT_CNO` int(11) DEFAULT NULL,
  `MASTER_YN` varchar(2) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`EMAIL`,`MEMBER_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `CHAT_CONTENTS` (
  `MASTER_SEQ` int(11) NOT NULL,
  `CONTENTS_SEQ` int(11) NOT NULL,
  `CONTENTS` varchar(2000) DEFAULT NULL,
  `CHAT_DIV` varchar(30) DEFAULT NULL,
  `REG_ID` varchar(2000) DEFAULT NULL,
  `REG_DATE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`MASTER_SEQ`,`CONTENTS_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `CHAT_MASTER` (
  `MASTER_SEQ` int(11) NOT NULL,
  `CHAT_ROOM_NAME` varchar(2000) DEFAULT NULL,
  `REG_ID` varchar(2000) DEFAULT NULL,
  `REG_DATE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`MASTER_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `CHAT_MEMBER` (
  `MASTER_SEQ` int(11) NOT NULL,
  `MEMBER_SEQ` int(11) NOT NULL,
  `CHAT_USER` varchar(2000) DEFAULT NULL,
  `MASTER_DIV` varchar(10) DEFAULT NULL,
  `REG_ID` varchar(2000) DEFAULT NULL,
  `REG_DATE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`MASTER_SEQ`,`MEMBER_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `CHAT_READ_HISTORY` (
  `CONTENTS_SEQ` int(11) NOT NULL,
  `MEMBER_SEQ` int(11) NOT NULL,
  `READ_DATE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`MEMBER_SEQ`,`CONTETNS_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ex1.V_CHAT_LAST_CONTENTS_LIST
SELECT A.MASTER_SEQ, A.CONTENTS, REG_DATE
FROM ex1.CHAT_CONTENTS A,
(SELECT MASTER_SEQ, MAX(CONTENTS_SEQ) SEQ
FROM ex1.CHAT_CONTENTS 
GROUP BY MASTER_SEQ) B
WHERE A.MASTER_SEQ = B.MASTER_SEQ AND A.CONTENTS_SEQ = B.SEQ;


