CREATE TABLE color_memo.MINESWEEPER (
    SEQ				INT NOT NULL,     
    SCORE           VARCHAR(2000) NOT NULL,
    CLICK_CNT		VARCHAR(2000),
    PLAY_TIME		VARCHAR(2000),
    NAME			VARCHAR(2000),
    REGDAY			DATE,
    PRIMARY KEY (SEQ)
);

CREATE SEQUENCE color_memo.MINE_SEQ
start with 1
increment by 1
maxvalue 999999
cycle;

SELECT * FROM color_memo.MINESWEEPER ORDER BY SCORE, REGDAY;
SELECT SEQ, CONVERT(SCORE, FLOAT) AS SCORE, CLICK_CNT, PLAY_TIME, NAME, DATE_FORMAT(REGDAY,'%Y년 %m월 %d일') AS REGDAY FROM color_memo.MINESWEEPER ORDER BY SCORE DESC, REGDAY;

SELECT * FROM color_memo.MINESWEEPER;
SELECT LASTVAL(color_memo.MINE_SEQ);


